services:
  wallet_app:
    container_name: wallet_app
    image: damedelion/rest_wallet
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres

  postgres:
    container_name: wallet_db
    image: postgres:17
    env_file:
      - config.env

    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data

volumes:
  pgdata:
