server:
  port: 8080

db:
  host: postgres
  port: 5432
  user: postgres
  password: postgres
  dbname: wallet_db
  sslmode: disable
  timezone: Europe/Moscow
  maxOpenConns: 60
  connMaxLifetime: 120
  maxIdleConns: 30
  connMaxIdleTime: 20
